<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Microchip TCP/IP Stack Demo App for STM32</title>
<link href="/mchp.css" rel="stylesheet" type="text/css" />
<script src="/mchp.js" type="text/javascript"></script>
</head>

<body>
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">
<table border="0">
<tr>
	<td align="left"><img src="/mchp.gif" alt="Microchip" /></td>
	<td align="left"><img src="/st.gif" alt="Microchip" /></td>
</tr>
</table>
<div id="title"><div class="right">TCP/IP Stack Demo Application for STM32</div><span id="hello">&nbsp;</span></div>

<div id="menu">
<a href="/index.htm">Overview</a>
<a href="/dynvars.htm">Dynamic Variables</a>
<a href="/forms.htm">Form Processing</a>
<a href="/auth.htm">Authentication</a>
<a href="/cookies.htm">Cookies</a>
<a href="/upload.htm">File Uploads</a>
<a href="/email">Send E-mail</a>
<a href="/dyndns">Dynamic DNS</a>
<a href="/protect/config.htm">Network Configuration</a>
<a href="/snmp/snmpconfig.htm">SNMP Configuration</a>
</div>